const bcrypt = require("bcrypt");

const password = "12345678";
const encryptedPassword = bcrypt.hashSync(password, 10);

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "user",
      //user_name, user_last_name, mail, password, birthdate, address, phone
      [
        {
          user_name: "Admin",
          user_last_name: "Administrator",
          email: "aadminh@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1996-10-23",
          address: "Callum st, Sidney",
          phone: "486580503",
          role_id: 1,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Philip",
          user_last_name: "Sherman",
          email: "P.ShermanDoctorh@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1996-10-23",
          address: "42 Wallaby Way, Sidney",
          phone: "488870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Karl",
          user_last_name: "Larrson",
          email: "KarltheKhan@kolaemail.com",
          password: encryptedPassword,
          birthdate: "2000-05-09",
          address: "87 George Street, Sidney",
          phone: "488670501",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Laura",
          user_last_name: "Palmer",
          email: "TwinPeaks@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1972-06-22",
          address: "74 Woodbury St., Sidney",
          phone: "482870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Robert",
          user_last_name: "Smith",
          email: "SmithRobert@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1999-09-09",
          address: "89 Darley St, Sidney",
          phone: "488070503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Smith",
          user_last_name: "Robert",
          email: "RoberSmith@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1984-08-12",
          address: "21 Crawford St., Sidney",
          phone: "487870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Mark",
          user_last_name: "Cross",
          email: "TheMarkCross@koalaemail.com",
          password: encryptedPassword,
          birthdate: "2005-06-23",
          address: " 01 Marrick road, Sidney",
          phone: "405470503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Namitia",
          user_last_name: "Delawere",
          email: "RiverDelamitia@koalaemail.com",
          password: encryptedPassword,
          birthdate: "2001-12-06",
          address: "45 Durham St., Sidney",
          phone: "408870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Herbert",
          user_last_name: "Reeks",
          email: "HerbertReeks9@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1946-06-15",
          address: "87 New Canterbury Road, Sidney",
          phone: "488870003",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Roberta",
          user_last_name: "Flack",
          email: "Robertita864@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1985-09-18",
          address: "32 Dulwitch St.,Sidney",
          phone: "888870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Esperanza",
          user_last_name: "Spalding",
          email: "NottharEsperanza@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1973-10-03",
          address: "32 Dulwitch St.,Sidney",
          phone: "888870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Diana",
          user_last_name: "Krall",
          email: "DianaKrall09@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1964-09-16",
          address: "32 Dulwitch St.,Sidney",
          phone: "888870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        //patients
        {
          user_name: "Jack",
          user_last_name: "Room",
          email: "TheRoomJack@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1995-09-09",
          address: "23 Abergeldie St. , Sidney",
          phone: "788870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Tommy",
          user_last_name: "Wisseau",
          email: "YESTOMMY@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1955-10-03",
          address: "56 Arlington St., Sidney",
          phone: "488876503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Peter",
          user_last_name: "Eel",
          email: "PeterTheEel@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1998-11-28",
          address: "45 Seaview St., Sidney",
          phone: "418870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Rafael",
          user_last_name: "De Corazon",
          email: "Toreador@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1997-05-25",
          address: "21 Clissold St., Sidney",
          phone: "482870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Otto",
          user_last_name: "Hardestadt",
          email: "Ventrue@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1954-05-23",
          address: "33 Junction Rd, Sidney",
          phone: "488880503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Petrodon",
          user_last_name: "Seville",
          email: "Nosferatu@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1965-08-12",
          address: "35 Robert St., Sidney",
          phone: "388870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Theodor",
          user_last_name: "Bell",
          email: "Brujah@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1975-05-16",
          address: "55 Palace St., Sidney",
          phone: "488770503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Anatole",
          user_last_name: "Hersy",
          email: "Malkavian@koalaemail.com",
          password: encryptedPassword,
          birthdate: "2000-02-02",
          address: "22 Lasswade St., Sidney",
          phone: "486870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Lucita",
          user_last_name: "De Aragon",
          email: "Lasombra@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1996-12-12",
          address: "67 Cheviot St., Sidney",
          phone: "484870503",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Sascha",
          user_last_name: "Vykos",
          email: "Tzimisce@koalaemail.com",
          password: encryptedPassword,
          birthdate: "2001-01-01",
          address: "01 Duntan St., Sidney",
          phone: "488870553",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Thomas",
          user_last_name: "Becket",
          email: "Gangrel@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1965-09-09",
          address: "23 Regent St., Sidney",
          phone: "488870583",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Goratrix",
          user_last_name: "Spellbinder",
          email: "Tremere@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1954-03-12",
          address: "12 Carlisse St.,Sidney",
          phone: "488870507",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Fatima",
          user_last_name: "Al-Fakadhi",
          email: "Assamita@koalaemail.com",
          password: encryptedPassword,
          birthdate: "2001-06-03",
          address: "44 Macauley St. , Sidney",
          phone: "488870506",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Augusto",
          user_last_name: "Giovanni",
          email: "Giovanni@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1944-04-04",
          address: "44 Allen St., Sidney",
          phone: "488870505",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Hesha",
          user_last_name: "Ruhadze",
          email: "Setite@koalaemail.com",
          password: encryptedPassword,
          birthdate: "1986-09-09",
          address: "45 Perry St., Sidney",
          phone: "488870504",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
        {
          user_name: "Bort",
          user_last_name: "Bert",
          email: "nomoreplates@koalaemail.com",
          password: encryptedPassword,
          birthdate: "2003-09-09",
          address: "Garden Way",
          phone: "488870502",
          role_id: 2,

          updatedAt: new Date(),
          createdAt: new Date(),
        },
      ],
      {}
    );
  },
  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("users", {});
  },
};
